refactor ClusteringHandler
Project-Sustain/sustain-query-service pull request #112
Opened 2021-12-28 01:06 UTC by kierajost4

resolve #108

2021-12-29 19:12 UTC, menuka94 approved these changes
LGTM.

Need to be tested with the frontend.

2021-12-30 03:03 UTC, kierajost4 commented
I tested it with Delphi and it seems that all 4 clustering models are working the same as on master. Is there anything else i should test with on the frontend?

2021-12-30 15:42 UTC, inf0rmatiker requested changes
Most everything looks pretty good; I left 2 comments about the gRPC channel code being isolated to the `Handler` classes, and copied/pasted the comment wherever I saw that change needing to be made.

I didn't deep dive into how @menuka94 was actually building the Clustering models so some changes might need to be made there to accommodate large or sharded collections, but that's for another ticket.

2021-12-30 15:42 UTC, inf0rmatiker commented on src/main/java/org/sustain/handlers/spark/clustering/BisectingKMeansClusteringHandler.java
> +    public ClusteringTask createClusteringTask(StreamObserver<ModelResponse> responseObserver){
`Tasks` should not need to know about the gRPC channels at all, since they are independent of communication with the client. All they need to know is the information to perform their task; the `Handlers` will be responsible for communicating with the client over gRPC so that's the only place a `StreamObserver` should be seen.

2021-12-30 15:42 UTC, inf0rmatiker commented on src/main/java/org/sustain/handlers/spark/clustering/ClusteringHandler.java
> +				this.sparkManager.submit(this.createClusteringTask(responseObserver), "clustering-query");
See comment about `StreamObserver` being passed to `Tasks`

2021-12-30 15:42 UTC, inf0rmatiker commented on src/main/java/org/sustain/handlers/spark/clustering/ClusteringHandler.java
> +    public abstract ClusteringTask createClusteringTask(StreamObserver<ModelResponse> responseObserver);
See comment about `StreamObserver` being passed to `Tasks`

2021-12-30 15:42 UTC, inf0rmatiker commented on src/main/java/org/sustain/handlers/spark/clustering/GaussianMixtureClusteringHandler.java
> +    public ClusteringTask createClusteringTask(StreamObserver<ModelResponse> responseObserver){
See comment about `StreamObserver` being passed to `Tasks`

2021-12-30 15:42 UTC, inf0rmatiker commented on src/main/java/org/sustain/handlers/spark/clustering/KMeansClusteringHandler.java
> +    public ClusteringTask createClusteringTask(StreamObserver<ModelResponse> responseObserver){
See comment about `StreamObserver` being passed to `Tasks`

2021-12-30 15:42 UTC, inf0rmatiker commented on src/main/java/org/sustain/handlers/spark/clustering/LatentDirichletAllocationHandler.java
> +    public ClusteringTask createClusteringTask(StreamObserver<ModelResponse> responseObserver){
See comment about `StreamObserver` being passed to `Tasks`

2021-12-30 15:42 UTC, inf0rmatiker commented on src/main/java/org/sustain/server/SustainService.java
>      public void modelQuery(ModelRequest request, StreamObserver<ModelResponse> responseObserver) {
These changes are beautiful.

2021-12-30 15:42 UTC, inf0rmatiker commented on src/main/java/org/sustain/tasks/spark/clustering/BisectingKMeansClusteringTask.java
> +    public BisectingKMeansClusteringTask(ModelRequest modelRequest, StreamObserver<ModelResponse> responseObserver) {
See comment about `StreamObserver` being passed to `Tasks`

2021-12-30 15:42 UTC, inf0rmatiker commented on src/main/java/org/sustain/tasks/spark/clustering/BisectingKMeansClusteringTask.java
> +            responseObserver.onNext(ModelResponse.newBuilder()
See comment about `StreamObserver` being passed to `Tasks`

This code, which communicates back to the client, should be written _once_ in the `ClusteringHandler` class. It's the same for all clustering tasks, and we don't want repeated code everywhere

@menuka94

2021-12-30 15:42 UTC, inf0rmatiker commented on src/main/java/org/sustain/tasks/spark/clustering/GaussianMixtureClusteringTask.java
> +public class GaussianMixtureClusteringTask extends ClusteringTask {
See comment about `StreamObserver` being passed to `Tasks`, and communications with client being only in the `Handler` class.

2021-12-30 15:42 UTC, inf0rmatiker commented on src/main/java/org/sustain/tasks/spark/clustering/KMeansClusteringTask.java
> +public class KMeansClusteringTask extends ClusteringTask {
See comment about `StreamObserver` being passed to `Tasks`, and communications with client being only in the `Handler` class.

2021-12-30 15:42 UTC, inf0rmatiker commented on src/main/java/org/sustain/tasks/spark/clustering/LatentDirichletAllocationClusteringTask.java
> +public class LatentDirichletAllocationClusteringTask extends ClusteringTask {
See comment about `StreamObserver` being passed to `Tasks`, and communications with client being only in the `Handler` class.

2021-12-31 04:50 UTC, menuka94 commented
> I didn't deep dive into how @menuka94 was actually building the Clustering models so some changes might need to be made there to accommodate large or sharded collections, but that's for another ticket.

These clustering operations were only designed to run on a few aggregated collections. There was no necessity for running them on larger collections.

2022-01-03 19:59 UTC, kierajost4 commented on src/main/java/org/sustain/tasks/spark/clustering/BisectingKMeansClusteringTask.java
> +            responseObserver.onNext(ModelResponse.newBuilder()
The code is almost the same except it uses "BisectingKMeansResponse.newBuilder()" or the appropriate response type for the clusteringTask class it is in. I am confused how to reference these types in another way in the handler class that will work for all clustering tasks. Any ideas? 

This code is the reason why I thought I had to pass the responseObserver to the ClusteringTask classes.

2022-01-03 20:04 UTC, kierajost4 commented on src/main/java/org/sustain/tasks/spark/clustering/BisectingKMeansClusteringTask.java
> +            responseObserver.onNext(ModelResponse.newBuilder()
Never mind I think i can just use the "ModelResponse" type like the regression handler is doing.

2022-02-15 22:23 UTC, inf0rmatiker commented on src/main/java/org/sustain/handlers/spark/clustering/ClusteringHandler.java
>          return true;
lol

2022-02-15 22:24 UTC, inf0rmatiker commented on src/main/java/org/sustain/handlers/spark/regression/RegressionHandler.java
> +					this.request.getGisJoinsList(),
This is an artifact from moving `gisJoins` out of individual submodels requests (e.g. `RandomForestRegressionRequest`) and into the parent `ModelRequest`

2022-02-15 22:25 UTC, inf0rmatiker commented on src/main/proto/sustain.proto
@drg101  these are the changes made to the .proto

2022-02-17 16:36 UTC, merged