Implement all clustering algorithms
Project-Sustain/sustain-query-service pull request #50
Opened 2021-02-23 03:20 UTC by menuka94

Closes #45 #46 #47 #48

2021-03-08 14:10 UTC, hamersaw requested changes
there are logging issues. outside of that i can't comment on the correctness of the training process. i'm OK accepting it at face value.

2021-03-08 14:10 UTC, hamersaw commented on src/main/java/org/sustain/modeling/ClusteringQueryHandler.java
> +        log.info("results.size(): " + results.size());
we need to reach some consensus on logging levels. i don't think this should be logged at the info level.

2021-03-08 14:10 UTC, hamersaw commented on src/main/java/org/sustain/modeling/ClusteringQueryHandler.java
>          log.info("=======================================");
i don't see the value in logging this. certainly not at the info level.

2021-03-08 14:10 UTC, hamersaw commented on src/main/java/org/sustain/modeling/ClusteringQueryHandler.java
> +        Seq<String> features = convertListToSeq(featuresList);
this is certainly a temporary solution

2021-03-09 01:26 UTC, inf0rmatiker requested changes

2021-03-09 01:26 UTC, inf0rmatiker commented on src/main/java/org/sustain/handlers/ClusteringQueryHandler.java
> +        this.request = request;
Why are you reassigning this?
The call to `super(request, responseObserver)` assigns them to member variables of `GrpcHandler`, which you inherit.

2021-03-09 01:26 UTC, inf0rmatiker commented on src/main/java/org/sustain/handlers/ClusteringQueryHandler.java
> +    private void logRequest(ModelType modelType) {
Remove this function

2021-03-09 01:35 UTC, menuka94 commented on src/main/java/org/sustain/handlers/ClusteringQueryHandler.java
> +        this.request = request;
Oh I've missed that.

2021-03-09 02:30 UTC, inf0rmatiker approved these changes
We need to take a stab at a couple things this week:
- Providing an interface for model building
- Optimizing model building (reusing Spark Session, uploading deps in advance)
- Standardizing logging

Those should be delegated to a separate Issue though, so this branch is good to go.

2021-03-09 02:30 UTC, inf0rmatiker commented on src/main/resources/log4j.properties
> +# Root logger option
nice

2021-03-09 02:31 UTC, merged