added DirectQuery gRPC function
Project-Sustain/sustain-query-service pull request #56
Opened 2021-03-04 20:02 UTC by hamersaw

submits aggregation pipeline and returns results directly from MongoDB cluster without intermediate in-memory cache

2021-03-04 23:16 UTC, inf0rmatiker commented on src/main/java/org/sustain/querier/DirectQueryHandler.java
> +        log.debug("recv query for collection '"
Would be nice if this was a little more english, and used formatted logging:
`log.info("Received query for collection '{}'", request.getCollection());`

2021-03-04 23:17 UTC, inf0rmatiker commented on src/main/java/org/sustain/querier/DirectQueryHandler.java
> +		AtomicLong count = new AtomicLong(0);
Indentation got weird here

2021-03-04 23:21 UTC, inf0rmatiker commented on src/main/java/org/sustain/querier/DirectQueryHandler.java
> +        for (int i = 0; i < 1; i++) {
Not clear why this `for` loop is here, that only runs _once_.
I'm guessing this could be used to increase the number of `Thread`s that are spawned to pull results and create `DirectResponse`s, but if that's the case, we might want to use something like:
```
for (int threadIndex = 0; threadIndex < NUM_THREADS; threadIndex++) {
  ...
}
```

2021-03-04 23:22 UTC, inf0rmatiker commented on src/main/java/org/sustain/querier/DirectQueryHandler.java
> +            MongoClient mongo = new MongoClient(
There's already a class which does this, `db.mongodb.DBConnection`

2021-03-04 23:25 UTC, inf0rmatiker requested changes
Looks great as a PoC, but before this gets merged into `master` there needs to be some refactoring, especially of `handleDirectQuery()` to take some of the independent code chunks and put them into functions in order to decrease the length. The anonymous `Runnable` could also be named and put into a class with a proper name

2021-03-05 14:27 UTC, hamersaw commented
Applied requested changes in a new commit.

2021-03-05 14:49 UTC, inf0rmatiker approved these changes

2021-03-05 14:49 UTC, merged